<!DOCTYPE html>
<html lang="en">
<title>Privacy-page</title>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>

        .privacy-wrap ul{
            padding-left: 0;
        }

        .privacy-wrap ul,
        .privacy-wrap li{
            list-style-type: none;
        }

        .privacy-wrap li{
            margin-bottom: 20px;
        }

        .privacy-wrap .title{
            max-width: 600px;
            margin: 20px auto;
            font-size: 36px;
            text-align: center;
            font-weight: bold;
            line-height: 45px;
        }

        .privacy-deta{
            padding-top: 30px;
        }

        .privacy-content{
            padding-top: 10px;
        }

        .privacy-content p{
            font-size: 16px;
            text-align: justify;
            margin-bottom: 20px;
        }

        .privacy-list h3{
            font-size: 24px;
            font-weight: bolder;
        }

        @media (max-width:768px){
            .privacy-wrap .title{
            max-width: 100%;
            font-size: 25px;
            line-height: 30px;
        }

        .privacy-list h3{
            font-size: 18px;
            font-weight: bolder;
        }

        .privacy-deta{
            padding-top: 10px;
        }
        
        }
    </style>
</head>
<body>
    <section class="privacy-wrap">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="privacy-deta">
                        <h2 class="title">Privacy Preamble</h2>
                        <div class="privacy-content">
                            <p>We at SilwanaInfotech , are committed to protecting your privacy. This Privacy Policy applies to our website (https://silwanainfotech.com/) and our Subscription Service (Subscription for regular IT news and happenings), including our associated mobile applications (Mobile Apps) owned and controlled by Hidden Brains. This Privacy Policy governs our data collection, processing and usage practices. It also describes your choices regarding use, access and correction of your personal information. If you do not agree with the data practices described in this Privacy Policy, you should not use the Websites or the Subscription Service.</p>
                            <p>This legal document is an electronic record in terms of India’s Information Technology Act, 2000, and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                            <p>This legal document is published in accordance with the provisions of Rule 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the privacy policy for access or usage of https://silwanainfotech.com/</p>
                            <p>This privacy policy applies to all users and subscribers of our websites.</p>
                            <p>By using this website, or completing the contact registration process through offline mode, you agree and acknowledge that you have carefully read this privacy policy and accepted this agreement.</p>
                            <p>References in these Terms to "we" or "us" or “website” or “company” or “HiddenBrains” are references to www.hiddenbrains.com and “you” as subscriber/user of a website.</p>
                        </div>
                    </div>
                    <div class="privacy-deta">
                        <h2 class="title">Personal Information We Collect</h2>
                        <div class="privacy-content">
                            <p>While providing information for various web development services, the issue of online privacy is extremely crucial for Hidden Brains, which is committed for safeguarding the information provided by its users. We are dedicated to create a reasonably secured environment for our users.</p>
                            <p>Respecting privacy of its online users while providing top-of-the-line services have always been the core strategies of Hidden Brains. Our Privacy Policy gives users a view of the Privacy Practices followed by us and assures them of safe passage through the website.</p>
                            <p>At the same time, we would like to make it clear that our website may provide links to other websites/apps that are governed by their own Privacy Policies and we do not take responsibility for the security and privacy provided by these sites/apps. This may include but are not limited to payment gateway sites. Users are urged to familiarize themselves with its Privacy Policy as well the policies of the third party sites/apps that collect personally identifiable information.</p>
                            <p>When you provide us with your personal data, you are agreeing to the rules and regulations stipulated under our Privacy Policy and are bound by it. If you do not agree to our Policy then please do not use our website.</p>
                        </div>
                    </div>
                    <div class="privacy-deta">
                        <h2 class="title">The Privacy Policy Shall be Governed In These Areas</h2>
                        <div class="privacy-content">
                            <p>Information you give us: During the process of Contact us/get in touch, you will be requested to complete a registration form asking for basic online contact information about yourself or provide us with your details over the phone, for example when you request for a quote on specific development service, register to attend one of our events (whether as a delegate, exhibitor or attendee) or subscribe to our mailing list. This information might include your name, address, email address, phone number and other relevant information. You agree and acknowledge that when we receive e-mails from you, we may retain the content of any e-mail messages sent to us, as well as details of your e-mail address. You further agree and acknowledge that we shall use your email ID and mobile number information for sending promotional/informational messages.</p>
                            <p>Information we collect about you: We will collect any information contained in any correspondence between you and us via contact forms on websites, and emails or telephone calls.</p>
                            <p>We may collect, for the purposes of service & solutions promotions and any events that we exhibit or participate, information about your location in and engagement with the event.</p>
                            <p>We collect information about you visiting our website and how you use it. This may include your IP address, geographical location, device information, browser type, referral source, length of visit, operating system, number of page views, which pages you viewed and similar information. This information may be collected by a third party website analytics service provider on our behalf and/or may be collected using cookies. We also use cookies and pixels in our emails to track delivery and open rates, the results of which are stored against your email address and profile.</p>
                            <p>We use third party analytics services for more detailed analytics purposes. It is important for us to inform you that we will have limited control over these Analytics and therefore you clearly agree and acknowledge that we shall not be held responsible for privacy issues relating to the same.</p>
                            <p>Information we receive from third parties: We may collect information about you from third parties that we work closely with for the purposes of delivering to you the services rendered by us. Third party entities may collect information directly from your websites or your digital presence. We may also receive information about you from third parties where you have consented to such third party sharing your information.</p>
                        </div>
                    </div>
                    <div class="privacy-deta">
                        <h2 class="title">We Collect Device Information Using the Following Technologies</h2>
                        <div class="privacy-content">
                            <p>“Cookies” are data files that are placed on your device or computer and often include an anonymous unique identifier. For more information about cookies, and how to disable cookies, visit http://www.allaboutcookies.org. “Log files” track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps. “Google Analytics” is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google servic</p>
                        </div>
                        <div class="privacy-list">
                            <h3>Cookies We Use:</h3>
                            <ul>
                                <li>Session Cookies: We use Session Cookies to operate our Service.Preference Cookies: We use Preference Cookies to remember your preferences and various settings.Security Cookies: We use Security Cookies for security purposes.</li>
                                <li>When we talk about “Personal Information” in this Privacy Policy, we are talking both about Device Information and Order Information.</li>
                            </ul>
                        </div>
                        <div class="privacy-list">
                            <h3>Do Not Track</h3>
                            <ul>
                                <li>Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.</li>
                            </ul>
                        </div>
                        <div class="privacy-list">
                            <h3>Your Rights:</h3>
                            <ul>
                                <li>If you are a European resident, you have the right to access the personal information we hold about you and to ask that your personal information is corrected, updated, or deleted. If you would like to exercise this right, please contact us through the contact information below.</li>
                            </ul>
                        </div>
                        <div class="privacy-list">
                            <h3>Changes</h3>
                            <ul>
                                <li>We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.</li>
                            </ul>
                        </div>
                        <div class="privacy-list">
                            <h3>Online Privacy Policy Only</h3>
                            <ul>
                                <li>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Intelivita. This policy is not applicable to any information collected offline or via channels other than this website.</li>
                            </ul>
                        </div>
                        <div class="privacy-list">
                            <h3>Consent</h3>
                            <ul>
                                <li>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>